version: "3"
services:
    db:
        image: groonga/pgroonga:latest
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            - "LANG=ja_JP.utf8"
        volumes:
            - ./pgsql-data:/var/lib/postgresql/data
    web:
        build:
            context: .
            dockerfile: Dockerfile_nginx
        volumes:
            - ./public:/usr/share/nginx/public:cached
        ports:
            - 80:80
        depends_on:
            - app
    app:
        build: .
        command: bundle exec rails server -b 0.0.0.0
        volumes:
            - ./:/myapp:cached
        depends_on:
            - db
        environment:
            RAILS_ENV: production
            SECRET_KEY_BASE: StudyBook
            MYAPP_DATABASE_PASSWORD: StudyBook
